# Generated by Django 6.0.3 on 2026-05-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehiTrack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date_expiration',
            field=models.DateField(blank=True, help_text="Date d'expiration", null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='type_document',
            field=models.CharField(choices=[('assurence', 'Assurence'), ('visite_technique', 'Visite_technique'), ('carte_grise', 'Carte_grise'), ('autre', 'Autre')], default='autre', max_length=50),
        ),
    ]
