# Generated by Django 6.0.3 on 2026-05-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehiTrack', '0004_alter_matricule_proprietaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricule',
            name='type_vehicule',
            field=models.CharField(blank=True, choices=[('camionnette', 'Camionnette'), ('suv', 'Suv'), ('camion', 'Camion'), ('voiture', 'Voiture'), ('autre', 'Autre')], max_length=20, null=True),
        ),
    ]
