# Generated by Django 6.0.3 on 2026-06-18 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehiTrack', '0005_matricule_type_vehicule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='contenu',
            new_name='contenu_du_document',
        ),
        migrations.RemoveField(
            model_name='document',
            name='matricule',
        ),
        migrations.AddField(
            model_name='document',
            name='plaque_d_immatricule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='VehiTrack.matricule'),
        ),
        migrations.AlterField(
            model_name='document',
            name='titre',
            field=models.CharField(choices=[('carte rose', 'carte rose'), ('permis de conduire', 'permis de conduire'), ('assurence', 'assurence'), ('controle technique', 'controle technique'), ('stationnement', 'stationnement'), ('vignette', 'vignette'), ('autorisation de transport(patente)', 'autorisation de transport(patente)')], default='titre du document', max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='type_document',
            field=models.CharField(choices=[('carte rose', 'carte rose'), ('permis de conduire', 'permis de conduire'), ('assurence', 'assurence'), ('controle technique', 'controle technique'), ('stationnement', 'stationnement'), ('vignette', 'vignette'), ('autorisation de transport(patente)', 'autorisation de transport(patente)')], default='autre', max_length=50),
        ),
    ]
