# Generated by Django 6.0.4 on 2026-07-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehiTrack', '0006_rename_contenu_document_contenu_du_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type_document',
            field=models.CharField(choices=[('carte rose', 'carte rose'), ('permis de conduire', 'permis de conduire'), ('assurence', 'assurence'), ('controle technique', 'controle technique'), ('stationnement', 'stationnement'), ('vignette', 'vignette'), ('autorisation de transport(patente)', 'autorisation de transport(patente)')], default='carte rose', max_length=50),
        ),
    ]
