# Generated by Django 6.0.4 on 2026-07-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehiTrack', '0007_alter_document_type_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='titre',
            field=models.CharField(choices=[('carte rose', 'carte rose'), ('permis de conduire', 'permis de conduire'), ('assurence', 'assurence'), ('controle technique', 'controle technique'), ('stationnement', 'stationnement'), ('vignette', 'vignette'), ('autorisation de transport(patente)', 'autorisation de transport(patente)'), ('autre', 'Autre')], default='titre du document', max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='type_document',
            field=models.CharField(choices=[('carte rose', 'carte rose'), ('permis de conduire', 'permis de conduire'), ('assurence', 'assurence'), ('controle technique', 'controle technique'), ('stationnement', 'stationnement'), ('vignette', 'vignette'), ('autorisation de transport(patente)', 'autorisation de transport(patente)'), ('autre', 'Autre')], default='carte rose', max_length=50),
        ),
    ]
